# Generated by Django 4.2.1 on 2023-06-06 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Castomer',
            new_name='Customer',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
